#!/usr/bin/env bash
set -euo pipefail

# ANSI escape codes.
BOLD='\033[1m'
CYAN='\033[36m'
MAGENTA='\033[35m'
RESET='\033[0m'

main() {
  print_step "Checking code formatting"
  mix format --check-formatted
  print_done

  print_step "Running test suite"
  mix test
  print_done

  print_step "Running static analysis"
  mix credo
  print_done

  print_step "Git push"
}

print_step() {
  local -r description="$1"
  echo -e "${MAGENTA}${BOLD}### ${description} ###${RESET}"
}

print_done() {
  echo -e "${CYAN}Done.${RESET}"
  echo
}

main
